0:
  src: "/images/usecases/environment-monitoring/em1.webp"
  alt: "environment monitoring 1"
1:
  src: "/images/usecases/environment-monitoring/em2.png"
  alt: "environment monitoring 2"
2:
  src: "/images/usecases/environment-monitoring/em3.png"
  alt: "environment monitoring 3"