0:
  id: "data-visualization"
  height: "416px"
  crisp:
    0:
      faIcon: "far fa-clock"
      text: "8 hours"
    1:
      src: "/images/trainings/icon_hat-graduation.svg"
      text: "4 sessions"
  title: "Data visualization"
  description: "Clear and simple introduction to data visualization tools and how to create custom widgets"
  linkLabel: "More about the course below"
  linkId: "data-visualization"
1:
  id: "administration"
  height: "416px"
  crisp:
    0:
      faIcon: "far fa-clock"
      text: "2 hours"
    1:
      src: "/images/trainings/icon_hat-graduation.svg"
      text: "1 session"
  title: "ThingsBoard administration"
  description: "Basic understanding of installation, configuration, and maintenance for effective platform administration."
  linkLabel: "More about the course below"
  linkId: "administration"
2:
  id: "scada"
  height: "416px"
  crisp:
    0:
      faIcon: "far fa-clock"
      text: "8 hours"
    1:
      src: "/images/trainings/icon_hat-graduation.svg"
      text: "4 sessions"
  title: "SCADA system"
  description: "Detailed guide to creating dashboards for SCADA systems, including layout and configuration settings."
  linkLabel: "More about the course below"
  linkId: "scada"
3:
  id: "management"
  height: "416px"
  crisp:
    0:
      faIcon: "far fa-clock"
      text: "12 hours"
    1:
      src: "/images/trainings/icon_hat-graduation.svg"
      text: "6 sessions"
  title: "Platform management and security"
  description: "Comprehensive overview of rule engine, alarm management, security model, and API usage."
  linkLabel: "More about the course below"
  linkId: "management"

